### ISSUE TITLE
Use a bigger batch size when downloading chunks

### ISSUE THREAD

**Issue by flagoworld** [marcoceppi/ibroadcast-dl#11]
It is recommended to use a length > 1 when downloading the library to do so in chunks. This will be a lot more efficient as zipping and unzipping individual tracks is slower for the server than streaming multiple tracks to a single zip. You can still download chunks concurrently.

```
        query = {
            "user_id": self.user_id(),
            "token": self.token(),
            "offset": offset,
            "length": length,  <----------------- set this to something like 20 or 40
            "container_type": "library",
            "mode": "downloadlibrary",
            "end_marker": 1,
        }
        resp = requests.get(build_url("/", query))
```

**Comment by marcoceppi** [comment]
The default from the [CLI is 50](https://github.com/marcoceppi/ibroadcast-dl/blob/main/ibroadcastdl/cli.py#L45), if someone is using the class directly they'd have to set it to something other than 1. I wasn't sure what a sane default would be for the library itself - and leave that up to whoever is implementing it.

If you have a suggestion for a default library level length I'm open to changing

**Comment by flagoworld** [comment]
Ah OK. I apologize, I missed that.
